# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b42b70d86ec32b18283d88f72b5cd4bf56fadc938723add5571f4cbdc4bd2ab9eb188f0e6a4f56f6694748204956b6f285cd3cff7ad5c374d63c8ed6f339de5

test:
  secret_key_base: 1bae1e0dad7fb4f5d45e07fb513a82f7725edbd6097cfde259eea64467279181c970330adc3c0df9ad1d57c964fe012c754aa98fbfa378042123216fc2c45c2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
